spring:
  datasource:
    password: password
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/
    username: SA
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    #show-sql: true
